### ISSUE TITLE
Compute Reference-based AM-FM Scores for Turn-level Dataset: dstc7

### ISSUE THREAD

**Issue by Jeiyoon** [e0397123/dstc10_metric_track#1]
Hi 😄

Thank you for your great works in advance.

I ran your code (compute_wr.py) and I've stuck in an error

```
--dataset=dstc7 --device=cuda:0 --am_model_path=embedding_models/full_am --fm_model_path=language_models/full_fm
Namespace(am_model_path='embedding_models/full_am', dataset='dstc7', device='cuda:0', fm_model_path='language_models/full_fm')
Some weights of BertModel were not initialized from the model checkpoint at embedding_models/full_am and are newly initialized: ['bert.pooler.dense.weight', 'bert.pooler.dense.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "/root/dstc10/dstc10_metric_track-main/baselines/deep_amfm/compute_wr.py", line 99, in <module>
    df = pd.json_normalize(json.load(f))
  File "/root/anaconda3/envs/dstc6/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/root/anaconda3/envs/dstc6/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/root/anaconda3/envs/dstc6/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/root/anaconda3/envs/dstc6/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 205402 column 6 (char 7060659)

Process finished with exit code 1
```

Evaluations on the other benchmarks work well, except "dstct7"

Here's the parameters

Thank you 😊

```
--dataset=dstc7
--device=cuda:0
--am_model_path=embedding_models/full_am
--fm_model_path=language_models/full_fm
```

**Comment by e0397123** [comment]
Does the problem occur for other dataset?

**Comment by e0397123** [comment]
I think this is most probably related to the data. I tried to run the code, but I couldn't reproduce your problem. Could you please double check the data? Try the following and see whether there is any problem? The total size of dstc7_eval.json file should be 8925942.

```
import json
dstc7_data = json.load(open('dstc7_eval.json', 'r'))
```

**Comment by Jeiyoon** [comment]
oh i double checked

It's "259742L, 8925943C" (8,717 KB) as your comment

and then I revisited the website [https://chateval.org/dstc10](https://chateval.org/dstc10) and downloaded evaluation datasets again

And It works well 🤣

I have no idea... anyway, everything's fine 

thank you so much!

Hope you have a great day!

**Comment by e0397123** [comment]
No problem. Glad you solved the issue. You too have a great day
